-- Database: db-test

-- DROP DATABASE IF EXISTS "db-test";

CREATE DATABASE "db-test"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'es_EC.UTF-8'
    LC_CTYPE = 'es_EC.UTF-8'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
    
-- SCHEMA: public

-- DROP SCHEMA IF EXISTS public ;

CREATE SCHEMA IF NOT EXISTS public
    AUTHORIZATION pg_database_owner;

COMMENT ON SCHEMA public
    IS 'standard public schema';

GRANT USAGE ON SCHEMA public TO PUBLIC;

GRANT ALL ON SCHEMA public TO pg_database_owner;

-- public.person definition

-- Drop table

-- DROP TABLE public.person;

CREATE TABLE public.person (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	address varchar(255) NOT NULL,
	age int4 NULL,
	gender varchar(25) NULL,
	identification varchar(10) NOT NULL,
	person_name varchar(255) NOT NULL,
	telephone varchar(15) NULL,
	CONSTRAINT person_pkey PRIMARY KEY (id)
);

-- public.client definition

-- Drop table

-- DROP TABLE public.client;

CREATE TABLE public.client (
	"password" varchar(255) NOT NULL,
	status bool NOT NULL,
	client_id int8 NOT NULL,
	CONSTRAINT client_pkey PRIMARY KEY (client_id)
);


-- public.client foreign keys

ALTER TABLE public.client ADD CONSTRAINT fkcxli0sgm0c24a09lfqwoi9wmt FOREIGN KEY (client_id) REFERENCES person(id);


-- public.account definition

-- Drop table

-- DROP TABLE public.account;

CREATE TABLE public.account (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	account_number varchar(255) NOT NULL,
	account_type varchar(255) NOT NULL,
	client_id int8 NOT NULL,
	initial_balance numeric(38,2) NOT NULL,
	status bool NOT NULL,
	CONSTRAINT account_account_type_check CHECK (((account_type)::text = ANY ((ARRAY['AHORROS'::character varying, 'CORRIENTE'::character varying])::text[]))),
	CONSTRAINT account_pkey PRIMARY KEY (id)
);


-- public.movement definition

-- Drop table

-- DROP TABLE public.movement;

CREATE TABLE public.movement (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	amount numeric(38,2) NOT NULL,
	"date" date NOT NULL,
	final_balance numeric(38,2) NOT NULL,
	initial_balance numeric(38,2) NOT NULL,
	movement_type varchar(255) NOT NULL,
	observation varchar(300) NULL,
	account_id int8 NULL,
	CONSTRAINT movement_movement_type_check CHECK (((movement_type)::text = ANY ((ARRAY['DEPOSITO'::character varying, 'RETIRO'::character varying])::text[]))),
	CONSTRAINT movement_pkey PRIMARY KEY (id)
);


-- public.movement foreign keys

ALTER TABLE public.movement ADD CONSTRAINT fkoemeananv9w9qnbcoccbl70a0 FOREIGN KEY (account_id) REFERENCES account(id);



